version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  traefik:
    image: traefik:v3.5.3
    environment:
      - CF_DNS_API_TOKEN=exlAF_0Iq7lt4UlJxbgoYvBDAVcLdg8DpgalM0Zi

    command:
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=letsencryptresolver"
      - "--entrypoints.websecure.forwardedHeaders.insecure=true"
      - "--certificatesresolvers.letsencryptresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencryptresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencryptresolver.acme.email=lucas.niquele.ln@gmail.com"
      - "--log.level=DEBUG"
      - "--accesslog=true"

    volumes:
      - "vol_certificates:/etc/traefik/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - gestao_network

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        
        # Dashboard do Traefik
        - "traefik.http.routers.traefik-dashboard.rule=Host(`container.towersfy.com`)"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.traefik-dashboard.priority=1000"
        - "traefik.http.routers.traefik-dashboard.middlewares=dash-redirect@swarm"

        # Redirecionamento para /dashboard/
        - "traefik.http.middlewares.dash-redirect.redirectregex.regex=^https?://container\\.towersfy\\.com/?$$"
        - "traefik.http.middlewares.dash-redirect.redirectregex.replacement=https://container.towersfy.com/dashboard/"

## --------------------------- ORION --------------------------- ##

volumes:
  vol_shared:
    external: true
    name: volume_swarm_shared
  vol_certificates:
    external: true
    name: volume_swarm_certificates

networks:
  gestao_network: ## Nome da rede interna
    external: true
    attachable: true
    name: gestao_network ## Nome da rede interna
